### ISSUE TITLE
px2rem-loader在npm的网站上关于webpack config的配置描述有误

### ISSUE THREAD

**Issue by seven-it** [Jinjiang/px2rem-loader#12]
![image](https://user-images.githubusercontent.com/23232041/39955665-956bcab2-5605-11e8-8674-dace78e2fdef.png)

正确参数应该是 remUint: 75 ,
错误地址：[https://www.npmjs.com/package/px2rem-loader](https://www.npmjs.com/package/px2rem-loader)
少了一个字母，错误的参数不会引起报错，在转换px值时使用的还是默认值remUint: 75
@Jinjiang

**Comment by Jinjiang** [comment]
`master` 分支已经修复了，因为不涉及代码变化，打算随下次代码变动的时候发不到 npm。
GitHub 上的 README.md 是正确的

**Comment by lizongwen** [comment]
参数配置什么意思有没有描述

**Comment by Jinjiang** [comment]
@lizongwen https://github.com/songsiqi/px2rem
