### ISSUE TITLE
px2rem有转换，但html标签没有设置font-size值。。

### ISSUE THREAD

**Issue by luffyzhao** [Jinjiang/px2rem-loader#15]
配置如下图：
![image](https://user-images.githubusercontent.com/4166371/40756334-92d9521a-64b5-11e8-94ca-5edf5c17f7a9.png)

**Comment by luffyzhao** [comment]
原来是要自己写。。 看了源码，都没做这块操作。。

**Comment by Jinjiang** [comment]
是的这里只做转换
谢谢
