### ISSUE TITLE
npm install px2rem-loader包安装失败

### ISSUE THREAD

**Issue by forest-green** [Jinjiang/px2rem-loader#17]
运行命令`npm install px2rem-loader` ，报错
`npm ERR! path D:\workSpace\develop\itm-wechat2\node_modules\.staging\ms-d86a17e7
npm ERR! code EEXIST
npm ERR! errno -4075
npm ERR! syscall mkdir
npm ERR! EEXIST: file already exists, mkdir 'D:\workSpace\develop\itm-wechat2\node_modules\.staging\ms-d86a17e7'
npm ERR! File exists: D:\workSpace\develop\itm-wechat2\node_modules\.staging\ms-d86a17e7
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\User\xxx\AppData\Roaming\npm-cache\_logs\2018-08-20T06_37_04_271Z-debug.log`

根据上面的错误提示，进行修改，再次安装依然报错

**Comment by Jinjiang** [comment]
对不齐我无法重现你的问题
