### ISSUE TITLE
whether it can add a ignore option

### ISSUE THREAD

**Issue by JlineZen** [Jinjiang/px2rem-loader#20]
We were happy to use px2rem-loader case it help us a lot, but we wonder whether it can add ignore option config when use it cause sometimes we want to import third party plugins but it was also computed the styles.

**Comment by Jinjiang** [comment]
You can easily modify the config field: `test: /\.css$/` or with [`exclude`](https://webpack.js.org/configuration/module/#rule-exclude) option together to customize the rules instead.
Thanks.
