### ISSUE TITLE
几个未能转换成功的场景

### ISSUE THREAD

**Issue by roy-lau** [Jinjiang/px2rem-loader#23]
1. 第三方的ui框架的css（如ionic/vux/Mint UI/Vant等）
2. html 中的 `style="height:800px" ;`
3. 使用js动态给dom添加的样式属性(class，style)

**Comment by DreamBuddy** [comment]
@roy-lau 本身就是只转换css文件中的静态px，js动态添加的又怎么能预处理呢

**Comment by roy-lau** [comment]
@DreamBuddy  等动态添加 `dom` 的样式的 `js`执行完后再执行 `px2rem-loader`。前两种情况应该算是静态的 `px` 吧

**Comment by DreamBuddy** [comment]
@roy-lau loader是预处理的 [百度-预处理器](https://baike.baidu.com/item/%E9%A2%84%E5%A4%84%E7%90%86/7833652?fr=aladdin)
你没法在js在浏览器中执行以后在执行px2rem-loader
前两种是静态的，但是.html文件不会被处理，第三方的我不太了解，猜测也是这个原因

**Comment by DreamBuddy** [comment]
@roy-lau  对于 js动态添加的其实很好处理， 举例:你添加某个 width:100px 这时候 自己计算一下 
'100/10'+'rem'

**Comment by roy-lau** [comment]
> 你没法在js在浏览器中执行以后在执行px2rem-loader
> 前两种是静态的，但是.html文件不会被处理，第三方的我不太了解，猜测也是这个原因

> 对于 js动态添加的其实很好处理， 举例:你添加某个 width:100px 这时候 自己计算一下
'100/10+'rem'

谢谢，get 到了 (_ps: 百度我比你熟儿，不用给我这种没有的链接_)
