### ISSUE TITLE
按照官方的语法推荐，去用，失效。

### ISSUE THREAD

**Issue by AnyGong** [Jinjiang/px2rem-loader#4]
按照官方的语法推荐，去用，失效。

[{ test: /\.vue$/, loader: vue.withLoaders({css: 'css!px2rem?remUnit=75&remPrecision=8'})}]

ReferenceError: vue is not defined

**Comment by Jinjiang** [comment]
应该和 vue-loader 版本升级有关，看看这个配置怎么样 http://vuejs.github.io/vue-loader/configurations/advanced.html 我稍后更新这边文档

**Comment by AnyGong** [comment]
@Jinjiang evry tks，已解决了我的问题

**Comment by dingcang** [comment]
@AnyGong 请问你是怎么解决的，非常感谢
